# SwiftLint Configuration for UI Component Standards

# Disable default rules that conflict with our standards
disabled_rules:
  - trailing_whitespace # We handle this differently
  - line_length # We use custom line length

# Enable additional rules
opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Custom rules for Design Token enforcement
custom_rules:
  no_direct_color_usage:
    name: "No Direct Color Usage"
    regex: '(?<!SemanticColor\.)Color\.(red|blue|green|black|white|gray|orange|yellow|purple|pink|primary|secondary)'
    message: "Use SemanticColor tokens instead of direct Color usage"
    severity: error
    
  no_direct_uicolor_usage:
    name: "No Direct UIColor Usage"
    regex: '(?<!SemanticColor\.)UIColor\.(red|blue|green|black|white|gray|orange|yellow|purple|systemBackground|secondarySystemBackground|label|secondaryLabel)'
    message: "Use SemanticColor tokens instead of direct UIColor usage"
    severity: error
    
  no_direct_font_usage:
    name: "No Direct Font Usage"  
    regex: '\.font\(\.(?:headline|subheadline|caption|caption2|title|title2|title3|body|footnote)\)'
    message: "Use Typography tokens instead of direct Font usage"
    severity: warning
    
  no_direct_spacing_usage:
    name: "No Direct Spacing Usage"
    regex: '\.padding\([0-9]+\)'
    message: "Use Spacing tokens instead of direct padding values"
    severity: warning
    
  no_direct_corner_radius:
    name: "No Direct Corner Radius"
    regex: '\.cornerRadius\([0-9]+\)'
    message: "Use CornerRadius tokens instead of direct values"
    severity: warning
    
  require_accessibility_labels:
    name: "Require Accessibility Labels"
    regex: 'Button\s*\('
    message: "Consider adding accessibility labels to interactive elements"
    severity: warning
    
  no_hardcoded_haptics:
    name: "No Hardcoded Haptics"
    regex: 'UIImpactFeedbackGenerator|UISelectionFeedbackGenerator|UINotificationFeedbackGenerator'
    message: "Use HapticManager instead of direct haptic feedback generators"
    severity: error

# Include/exclude configurations
included:
  - Delax100DaysWorkout/Components
  - Delax100DaysWorkout/Features  
  - Delax100DaysWorkout/Utils
  - Delax100DaysWorkout/Models
  - Delax100DaysWorkout/Services

excluded:
  - Delax100DaysWorkout/Legacy # Legacy code exempt from new rules
  - Scripts
  - .build
  - .git
  - Pods
  - Carthage
  - docs

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 300  # Enforce our 300-line rule
  error: 400

function_body_length:
  warning: 50
  error: 80

type_body_length:
  warning: 200
  error: 300

cyclomatic_complexity:
  warning: 10
  error: 15

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

# Naming conventions
type_name:
  min_length: 3
  max_length: 50

# Force unwrapping configuration  
force_unwrapping:
  severity: warning

# Multiline configuration
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  only_enforce_after_first_closure_on_first_line: true

# Collection alignment
vertical_parameter_alignment_on_call:
  severity: warning

# Closure spacing
closure_spacing:
  severity: warning

# Reporter type
reporter: "xcode"