name: 🏗️ Build Validation

on:
  workflow_call:

env:
  XCODE_VERSION: '15.4'
  IOS_SIMULATOR: 'iPhone 16 Pro'
  IOS_VERSION: 'latest'

jobs:
  swift-build:
    name: Swift Compilation
    runs-on: macos-14
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: 🔨 Build Project
      run: |
        xcodebuild build \
          -project Delax100DaysWorkout.xcodeproj \
          -scheme Delax100DaysWorkout \
          -destination 'platform=iOS Simulator,name=${{ env.IOS_SIMULATOR }},OS=${{ env.IOS_VERSION }}' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

  protocol-check:
    name: Protocol Architecture
    runs-on: macos-14
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - name: 🧬 Verify Protocol Infrastructure
      run: |
        # Verify Issue #75 Protocol-based architecture
        CRITICAL_FILES=(
          "Delax100DaysWorkout/Architecture/Protocols/CoreProtocols.swift"
          "Delax100DaysWorkout/Architecture/DI/DIContainer.swift" 
          "Delax100DaysWorkout/Architecture/Mocks/MockImplementations.swift"
        )
        
        for file in "${CRITICAL_FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file"
          else
            echo "❌ Missing: $file"
            exit 1
          fi
        done