name: ⚡ Performance Analysis

on:
  workflow_call:

env:
  XCODE_VERSION: '15.4'
  IOS_SIMULATOR: 'iPhone 16 Pro'
  IOS_VERSION: 'latest'

jobs:
  build-performance:
    name: Build Speed Test
    runs-on: macos-14
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: ⚡ Measure Build Time
      run: |
        START_TIME=$(date +%s)
        
        xcodebuild build \
          -project Delax100DaysWorkout.xcodeproj \
          -scheme Delax100DaysWorkout \
          -destination 'platform=iOS Simulator,name=${{ env.IOS_SIMULATOR }},OS=${{ env.IOS_VERSION }}' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -quiet
        
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        echo "🕐 Build time: ${DURATION}s"
        
        if [ $DURATION -lt 120 ]; then
          echo "✅ Excellent performance"
        elif [ $DURATION -lt 300 ]; then
          echo "⚠️ Acceptable performance"
        else
          echo "❌ Performance needs optimization"
          exit 1
        fi